const data = [
    { image: "" },
    { marbles: 5 + 02, image: "images/45633.jpg", name: " " },
    { marbles: 5 + 02, image: "images/31878.jpg", name: " " },
    { marbles: 5 + 02, image: "images/31785.jpg", name: " " },
    { marbles: 5 + 06, image: "images/35244.jpg", name: " " },
    { marbles: 5 + 00, image: "images/35607.jpg", name: " " },
    { marbles: 5 + 07, image: "images/35035.jpg", name: " " },
    { marbles: 5 + 02, image: "images/34713.jpg", name: " " },
    { marbles: 5 + 02, image: "images/34702.jpg", name: " " },
    { marbles: 5 + 15, image: "images/46245.jpg", name: " " },
    { marbles: 5 + 08, image: "images/34999.jpg", name: " " },
    { marbles: 5 + 03, image: "images/34960.jpg", name: " " },
    { marbles: 5 + 07, image: "images/45336.jpg", name: " " },
    { marbles: 5 + 05, image: "images/31663.jpg", name: " " },
    { marbles: 5 + 05, image: "images/46068.jpg", name: " " },
    { marbles: 5 + 08, image: "images/34872.jpg", name: " " },
    { marbles: 5 + 02, image: "images/32387.jpg", name: " " },
    { marbles: 5 + 06, image: "images/32106.jpg", name: " " },
    { marbles: 5 + 05, image: "images/31686.jpg", name: " " },
    { marbles: 5 + 02, image: "images/46035.jpg", name: " " },
    { marbles: 5 + 07, image: "images/34834.jpg", name: " " },
    { marbles: 5 + 10, image: "images/34970.jpg", name: " " },
    { marbles: 5 + 00, image: "images/45241.jpg", name: " " },
    { marbles: 5 + 06, image: "images/35065.jpg", name: " " },
    { marbles: 5 + 05, image: "images/34918.jpg", name: " " },
    { marbles: 5 + 05, image: "images/34385.jpg", name: " " },
    { marbles: 5 + 08, image: "images/35138.jpg", name: " " },
    { marbles: 5 + 00, image: "images/34406.jpg", name: " " },
    { marbles: 5 + 05, image: "images/34484.jpg", name: " " },
    { marbles: 5 + 08, image: "images/46053.jpg", name: " " },
    { marbles: 5 + 11, image: "images/34419.jpg", name: " " },
    { marbles: 5 + 09, image: "images/34714.jpg", name: " " },
    { marbles: 5 + 07, image: "images/35030.jpg", name: " " },
    { marbles: 5 + 05, image: "images/34538.jpg", name: " " },
    { marbles: 5 + 08, image: "images/34550.jpg", name: " " },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" }
];