const data = [
    { image: "" },
    { marbles: 5+2, image: "images/45633.jpg", name: " " },
    { marbles: 5+2, image: "images/31785.jpg", name: " " },
    { marbles: 5 + 6+3, image: "images/35244.jpg", name: " " },
    { marbles: 5, image: "images/35607.jpg", name: " " },
    { marbles: 5 + 2+3, image: "images/35035.jpg", name: " " },
    { marbles: 5 + 6+4, image: "images/32032.jpg", name: " " },
    { marbles: 5+4, image: "images/34713.jpg", name: " " },
    { marbles: 5+2, image: "images/34702.jpg", name: " " },
    { marbles: 5 + 3, image: "images/46245.jpg", name: " " },
    { marbles: 5+2, image: "images/34524.jpg", name: " " },
    { marbles: 5 + 5+9, image: "images/34378.jpg", name: " " },
    { marbles: 5 + 7+6, image: "images/45336.jpg", name: " " },
    { marbles: 5 + 1+2, image: "images/46068.jpg", name: " " },
    { marbles: 5, image: "images/34872.jpg", name: " " },
    { marbles: 5 + 6+6, image: "images/32387.jpg", name: " " },
    { marbles: 5 + 2+4, image: "images/32047.jpg", name: " " },
    { marbles: 5, image: "images/32106.jpg", name: " " },
    { marbles: 5+2, image: "images/46035.jpg", name: " " },
    { marbles: 5+2, image: "images/34834.jpg", name: " " },
    { marbles: 5+2, image: "images/45241.jpg", name: " " },
    { marbles: 5 + 2+5, image: "images/34830.jpg", name: " " },
    { marbles: 5 + 1+6, image: "images/35065.jpg", name: " " },
    { marbles: 5+2, image: "images/34918.jpg", name: " " },
    { marbles: 5 + 3+4, image: "images/31767.jpg", name: " " },
    { marbles: 5 + 4+4, image: "images/34406.jpg", name: " " },
    { marbles: 5 + 3+3, image: "images/34484.jpg", name: " " },
    { marbles: 5+2, image: "images/46053.jpg", name: " " },
    { marbles: 5+3, image: "images/34714.jpg", name: " " },
    { marbles: 5 + 1+3, image: "images/35030.jpg", name: " " },
    { marbles: 5 + 4+5, image: "images/34538.jpg", name: " " },
    { marbles: 5 + 2+5, image: "images/34550.jpg", name: " " },
    { marbles: 5+2, image: "images/36600.jpg", name: " " },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" },
    { marbles: 4, image: "./images/m7.jpg" },
    { marbles: 8, image: "./images/m8.jpg" },
    { marbles: 8, image: "./images/m9.jpg" },
    { marbles: 8, image: "./images/m10.jpg" },
    { marbles: 3, image: "./images/m1.jpg" },
    { marbles: 3, image: "./images/m2.jpg" },
    { marbles: 3, image: "./images/m3.jpg" },
    { marbles: 3, image: "./images/m4.jpg" },
    { marbles: 3, image: "./images/m5.jpg" },
    { marbles: 3, image: "./images/m6.jpg" }
];
